#!/usr/bin/env sh
#
# Formats the C# in the AudioLink package according to .editorconfig.
#
#   ./format.sh              # rewrite files in place
#   ./format.sh --check      # report violations, change nothing, non-zero exit
#
# Requires the .NET SDK 6 or newer: https://dotnet.microsoft.com/download
#
# Why this doesn't use the .sln files like the old version did:
#
#   The old script ran `dotnet format` against AudioLink{,Web,Sandbox}UnityProject.sln.
#   Those solutions are generated by Unity and are gitignored, so the script only
#   worked if you had opened every project locally first, and it could never run in
#   CI. It also pulled in every vendored dependency the sandbox happens to contain
#   (LTCGI, Texel, Thry, cnlohr, Airtime, the VPM resolver package), none of which
#   are ours to reformat, and AudioLinkUnityProject has no first-party C# at all.
#
#   `dotnet format whitespace --folder` needs no project or solution, so we point it
#   directly at the code we own. Add a path to FORMAT_PATHS to widen the scope.
#
# Note that this only applies whitespace rules (indentation, spacing, newlines,
# final newline). The analyzer-driven style rules in .editorconfig still need a
# compiled project, which means Unity, which means your IDE rather than CI.

set -eu

cd "$(dirname "$0")"

FORMAT_PATHS="Packages/com.llealloo.audiolink"

# Deliberately not formatted:
#   AudioLinkSandboxUnityProject/Assets  - mostly vendored third-party prefabs
#   AudioLinkUnityProject/Assets         - contains no first-party C#
#   AudioLinkWebProject/Assets           - single file, shares the sandbox's history

if ! command -v dotnet > /dev/null 2>&1; then
    echo "error: dotnet not found on PATH." >&2
    echo "       install the .NET SDK from https://dotnet.microsoft.com/download" >&2
    exit 1
fi

# The dotnet host alone isn't enough, `dotnet format` ships with the SDK.
if [ -z "$(dotnet --list-sdks 2> /dev/null)" ]; then
    echo "error: a .NET runtime is installed but no SDK, so dotnet format is unavailable." >&2
    echo "       install the .NET SDK from https://dotnet.microsoft.com/download" >&2
    exit 1
fi

ARGS=""
for arg in "$@"; do
    case "$arg" in
        --check) ARGS="$ARGS --verify-no-changes" ;;
        *) ARGS="$ARGS $arg" ;;
    esac
done

status=0
for path in $FORMAT_PATHS; do
    echo "==> $path"
    # shellcheck disable=SC2086
    dotnet format whitespace "$path" --folder $ARGS || status=$?
done

exit $status
