on: push

jobs:

  build-minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p Assets/AudioLink/Editor/Scripts
 
        cp -R Packages/com.llealloo.audiolink/Runtime/* Assets/AudioLink/

        cp LICENSE* Assets/AudioLink/
        cp README.md* Assets/AudioLink/
        cp CHANGELOG.md* Assets/AudioLink/

        rm Assets/AudioLink/AudioLink.asmdef
        rm Assets/AudioLink/AudioLink.asmdef.meta

        find Assets/AudioLink/Shaders/ -type f -exec sed -i 's/#include "Packages\/com\.llealloo\.audiolink\/Runtime/#include "Assets\/AudioLink/g' {} +

        echo "Assets/AudioLink/AudioLink.prefab.meta" >> metaList
        echo "Assets/AudioLink/AudioLinkAvatar.prefab.meta" >> metaList
        echo "Assets/AudioLink/AudioLinkController.prefab.meta" >> metaList
        echo "Assets/AudioLink/LICENSE.meta" >> metaList
        echo "Assets/AudioLink/README.md.meta" >> metaList
        echo "Assets/AudioLink/VERSION.txt.meta" >> metaList
        echo "Assets/AudioLink/CHANGELOG.md.meta" >> metaList

        echo "Assets/AudioLink/Scripts.meta" >> metaList
        find "Assets/AudioLink/Scripts/" -name \*.meta >> metaList
        echo "Assets/AudioLink/RenderTextures.meta" >> metaList
        find "Assets/AudioLink/RenderTextures/" -name \*.meta >> metaList
        echo "Assets/AudioLink/Shaders.meta" >> metaList
        find "Assets/AudioLink/Shaders/" -name \*.meta >> metaList
        echo "Assets/AudioLink/Materials.meta" >> metaList
        find "Assets/AudioLink/Materials/" -name \*.meta >> metaList
        echo "Assets/AudioLink/Resources.meta" >> metaList
        find "Assets/AudioLink/Resources/" -name \*.meta >> metaList
    - run: mkdir build
    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'build/minimal.unitypackage'
        include-files: metaList
    - uses: kittaakos/upload-artifact-as-is@v0
      with:
        path: build/